"""more

Revision ID: 164b39a8531a
Revises: a8e10748b274
Create Date: 2023-06-25 10:28:19.436597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164b39a8531a'
down_revision = 'a8e10748b274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['developer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('developer_id')

    # ### end Alembic commands ###
