"""more

Revision ID: 29dd46a916ca
Revises: 89e52b3dafe3
Create Date: 2023-06-30 21:00:07.801401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dd46a916ca'
down_revision = '89e52b3dafe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pictures_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pictures_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
