"""more

Revision ID: 72930ac275c5
Revises: 4e85f41b65f4
Create Date: 2023-06-23 19:59:12.502672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72930ac275c5'
down_revision = '4e85f41b65f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
